<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NX00483" failures="1" tests="7" name="Testcases_Package.ValidateLoginPage" time="111.835" errors="0" timestamp="2022-11-02T18:18:41 PKT" skipped="0">
  <testcase classname="Testcases_Package.ValidateLoginPage" name="TestcasetoVerifyLoginwithbothcorrectUsernameandPassword" time="8.723"/>
  <system-out/>
  <testcase classname="Testcases_Package.ValidateLoginPage" name="TestcasetoVerifyLoginwith_CorrectUsernameandWrongPassword" time="16.638"/>
  <system-out/>
  <testcase classname="Testcases_Package.ValidateLoginPage" name="TestcasetoVerifyLoginwith_bothWrongUsernameandPassword" time="15.757"/>
  <system-out/>
  <testcase classname="Testcases_Package.ValidateLoginPage" name="TestcasetoVerifyLoginwith_WrongUsernameandCorrectPassword" time="15.373">
    <failure message="Failed expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Testcases_Package.ValidateLoginPage.TestcasetoVerifyLoginwith_WrongUsernameandCorrectPassword(ValidateLoginPage.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TestcasetoVerifyLoginwith_WrongUsernameandCorrectPassword -->
  <system-out/>
  <testcase classname="Testcases_Package.ValidateLoginPage" name="TestcasetoVerifyLoginwithbothcorrectUsernameandPassword" time="12.956"/>
  <system-out/>
  <testcase classname="Testcases_Package.ValidateLoginPage" name="TestcasetoVerifyLoginwithbothcorrectUsernameandPassword" time="18.102"/>
  <system-out/>
  <testcase classname="Testcases_Package.ValidateLoginPage" name="TestcasetoVerifyLoginwithbothcorrectUsernameandPassword" time="24.286"/>
  <system-out/>
</testsuite> <!-- Testcases_Package.ValidateLoginPage -->
